icon: assets/icon/ic_app.png
summary: 时间管理助手
group: Development/Tools
vendor: Zinc
packager: Zinc
packagerEmail: zinc233@qq.com
license: GPLv2
url: https://todo.zinc233.top

display_name: 时间管理助手

keywords:
  - Todo
  - Time
  - Application

generic_name: 时间管理助手

categories:
  - utils

startup_notify: true

