name: Build Linux Application

on:
  push:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build-on-linux:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - shell: bash
        run: |
          echo -e "DS_KEY=$DS_KEY       \n"  > .env
          echo -e "SUPA_URL=$SUPA_URL   \n" >> .env
          echo -e "SUPA_ANON=$SUPA_ANON"    >> .env

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev locate rpm patchelf locate p7zip libfuse2

          wget -O appimagetool "https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage"
          chmod +x appimagetool
          sudo mv appimagetool /usr/local/bin/

      - run: |
          flutter --version
          flutter pub get

      - run: |
          mkdir dist
          dart pub global activate flutter_distributor
          dart run build_runner clean
          dart run build_runner build -d 1 -r
          dart run flutter_launcher_icons

      - run: flutter_distributor package --platform linux --targets deb,rpm,appimage,zip

      - run: ls -la dist/*/

      - uses: actions/upload-artifact@v4
        with:
          name: release_linux
          path: dist/*/*.*


  build-on-windows:
    name: Build Flutter Windows app
    runs-on: windows-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      
      - shell: bash
        run: |
          echo -e "DS_KEY=$DS_KEY       \n"  > .env
          echo -e "SUPA_URL=$SUPA_URL   \n" >> .env
          echo -e "SUPA_ANON=$SUPA_ANON"    >> .env

      - run: |
          mkdir dist
          dart pub global activate flutter_distributor
          dart run build_runner clean
          dart run build_runner build -d 1 -r
          dart run flutter_launcher_icons
                    
      - run: flutter_distributor package --platform windows --targets exe,msix

      - run: ls -la dist/*/

      - uses: actions/upload-artifact@v4
        with:
          name: release_windows
          path: dist/*/*.*

  build-on-macos:
    name: Build Flutter MacOs app
    runs-on: macos-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      
      - shell: bash
        run: |
          echo -e "DS_KEY=$DS_KEY       \n"  > .env
          echo -e "SUPA_URL=$SUPA_URL   \n" >> .env
          echo -e "SUPA_ANON=$SUPA_ANON"    >> .env

      - run: |
          npm install -g appdmg

      - run: |
          mkdir dist
          dart pub global activate flutter_distributor
          dart run build_runner clean
          dart run build_runner build -d 1 -r
          dart run flutter_launcher_icons
                    
      - run: flutter_distributor package --platform macos --targets dmg,pkg
      - run: ls -la dist/*/

      - uses: actions/upload-artifact@v4
        with:
          name: release_macos
          path: dist/*/*.*